import { Filter, Percent, Plus, Search, Sparkles, Ticket, TruckIcon, User, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { PageHeader } from "@/components/app/page-header";
import { DISCOUNTS, STORES } from "@/lib/mock";
import { formatCurrency, formatNumber } from "@/lib/utils";

const KIND_LABEL: Record<string, { label: string; icon: React.ComponentType<{ className?: string }> }> = {
  PERCENT:        { label: "% off",        icon: Percent },
  FIXED_AMOUNT:   { label: "€ off",        icon: Ticket },
  FREE_SHIPPING:  { label: "Free shipping",icon: TruckIcon },
};

const SOURCE_TONE: Record<string, "accent" | "muted"> = {
  manual: "muted",
  "flow:abandoned-cart": "accent",
  "flow:win-back": "accent",
  "flow:birthday": "accent",
  campaign: "accent",
};

export default function DiscountsPage() {
  const totalCodes = DISCOUNTS.length;
  const oneShot = DISCOUNTS.filter((d) => d.customerEmail).length;
  const totalUses = DISCOUNTS.reduce((s, d) => s + d.usedCount, 0);

  return (
    <div className="flex flex-col gap-5">
      <PageHeader
        title="Discounts"
        description="Per-recipient unique codes (auto-generated by flows) and shareable promo codes. Synced to Shopify Discount API at creation time."
        actions={
          <>
            <Button variant="outline" size="sm"><Sparkles className="h-3.5 w-3.5 text-[color:var(--accent)]" /> Generate batch</Button>
            <Button size="sm"><Plus className="h-3.5 w-3.5" /> New code</Button>
          </>
        }
      />

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
        <Stat label="Active codes" value={`${totalCodes}`} hint={`${oneShot} per-recipient · ${totalCodes - oneShot} shareable`} />
        <Stat label="Total uses" value={formatNumber(totalUses)} hint="across all stores · MTD" />
        <Stat label="Revenue attributed" value="€42,180" hint="orders that used a code · last 30d" tone="positive" />
        <Stat label="Avg discount given" value="€3.40" hint="per order using a code" />
      </div>

      <div className="flex flex-wrap items-center gap-2">
        <div className="relative max-w-sm flex-1">
          <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-muted-foreground" />
          <Input placeholder="Search by code or recipient email…" className="pl-8" />
        </div>
        <Button variant="ghost" size="sm"><Filter className="h-3.5 w-3.5" /> All sources</Button>
        <Button variant="ghost" size="sm">All stores</Button>
        <Button variant="ghost" size="sm">Active</Button>
      </div>

      <Card className="overflow-hidden p-0">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border bg-card text-[10px] uppercase tracking-wider text-muted-foreground">
                <th className="text-left font-medium px-5 py-2.5">Code</th>
                <th className="text-left font-medium px-3 py-2.5">Discount</th>
                <th className="text-left font-medium px-3 py-2.5">Store</th>
                <th className="text-left font-medium px-3 py-2.5">Bound to</th>
                <th className="text-left font-medium px-3 py-2.5">Source</th>
                <th className="text-left font-medium px-3 py-2.5">Usage</th>
                <th className="text-right font-medium px-5 py-2.5">Expires</th>
              </tr>
            </thead>
            <tbody>
              {DISCOUNTS.map((d) => {
                const store = STORES.find((s) => s.id === d.storeId)!;
                const Icon = KIND_LABEL[d.kind].icon;
                const usagePct = (d.usedCount / d.usageLimit) * 100;
                return (
                  <tr key={d.id} className="border-b border-border last:border-0 hover:bg-secondary/30 transition-colors">
                    <td className="px-5 py-2.5">
                      <div className="font-mono text-[12px] font-medium">{d.code}</div>
                      <div className="text-[10px] text-muted-foreground">Started {new Date(d.startsAt).toLocaleDateString("en-GB")}</div>
                    </td>
                    <td className="px-3 py-2.5">
                      <span className="inline-flex items-center gap-1.5 text-[12px]">
                        <Icon className="h-3 w-3 text-muted-foreground" />
                        {d.kind === "PERCENT" ? `${d.value}%` : d.kind === "FIXED_AMOUNT" ? formatCurrency(d.value, store.currency) : "Free shipping"}
                      </span>
                    </td>
                    <td className="px-3 py-2.5 text-[11px] text-muted-foreground">{store.name.replace("Divain ", "")}</td>
                    <td className="px-3 py-2.5">
                      {d.customerEmail ? (
                        <span className="inline-flex items-center gap-1.5 text-[11px]">
                          <User className="h-3 w-3 text-muted-foreground" />
                          <span className="truncate max-w-[180px]">{d.customerEmail}</span>
                        </span>
                      ) : (
                        <span className="inline-flex items-center gap-1.5 text-[11px] text-muted-foreground">
                          <Users className="h-3 w-3" /> Shareable
                        </span>
                      )}
                    </td>
                    <td className="px-3 py-2.5">
                      <Badge variant={SOURCE_TONE[d.source] ?? "muted"} className="font-mono text-[9px]">{d.source}</Badge>
                    </td>
                    <td className="px-3 py-2.5">
                      <div className="text-[11px] tabular-nums">{d.usedCount} / {d.usageLimit === 1 ? "1" : formatNumber(d.usageLimit)}</div>
                      <Progress value={Math.min(100, usagePct)} className="mt-1 w-24" />
                    </td>
                    <td className="px-5 py-2.5 text-right text-[11px] text-muted-foreground tabular-nums">
                      {d.endsAt ? new Date(d.endsAt).toLocaleDateString("en-GB") : "—"}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
}

function Stat({ label, value, hint, tone }: { label: string; value: string; hint: string; tone?: "positive" }) {
  return (
    <Card className="p-4">
      <div className="text-[11px] uppercase tracking-wider text-muted-foreground">{label}</div>
      <div className={`mt-1 text-[22px] font-medium tabular-nums ${tone === "positive" ? "text-[color:var(--positive)]" : ""}`}>{value}</div>
      <div className="text-[10px] text-muted-foreground">{hint}</div>
    </Card>
  );
}
